### ISSUE TITLE
Recommended to increase page layout to support the display of multiple pages at the same time.

### ISSUE THREAD

**Issue by gagmeng** [bornova/numara-calculator#53] opened 2024-04-23 00:55 UTC
As the title mentioned.

**Comment by bornova** [comment] 2024-04-23 18:30
Hi @gagmeng,
It is actually possible to have multiple windows open at the same time.  But the issue is that all windows share the same data storage, including calculations, settings, variables, etc.  So if a change is made in one window, it also changes the other windows but the change is not visible until the other pages are refreshed/restarted.  Then the UI becomes confusing.  Therefore I have chosen to keep a single window.  I will close this as `wontfix` for now however I will keep looking into a solution which would allow this in a user friendly way in the future.

Thank you for the suggestion!

**Closed by bornova** 2024-04-23 18:30 UTC
